### ISSUE TITLE
[CODE REVIEW] <siv2r>

### ISSUE THREAD

**Issue by siv2r** [imabp/code-review#12]
Hello, please help me with the code review for the following code sample.

Tech Stack: 
- [ ] JavaScript
- [x] Python
- [x] Others if yes, mention here : PHP

GitHub Link: https://github.com/siv2r/kidney-exchange

Thank you for this super-impacting initiative.
- [ ] I wish to donate [here](https://www.buymeacoffee.com/imabp) for your efforts, time, and support.

**Comment by imabp** [comment]
A huge chunk of code is commented. Remove it from production.
https://github.com/siv2r/kidney-exchange/blob/master/functions/json.func.php#L47-L91

Use GitHub Project Boards, to track features, instead of Readme
https://github.com/siv2r/kidney-exchange/blob/master/functions/scoringFunctions.md

Code Refactoring and organization are needed.

Include, website link in the repository about section and at top of the readme. It will be straight away out of the review panel. If no live link is there.  

I hope you will work on these points @siv2r . :)

**Comment by siv2r** [comment]
@imabp Thanks a lot. I will work on these.

>organization are needed

Do you mean like changing the architecture?

**Comment by imabp** [comment]
> @imabp Thanks a lot. I will work on these.
> 
> > organization are needed
> 
> Do you mean like changing the architecture?

@siv2r
I mean use decorator function and abstractors, and you call it from top level function. 
This makes sure, code is modular..
