### ISSUE TITLE
[CODE REVIEW]  <Naman-1234>

### ISSUE THREAD

**Issue by Naman-1234** [imabp/code-review#17]
Hello, please help me with the code review for the following code sample.
Hi @imabp, Please review this code sample. I am gonna continue working on this one to add New Features and improving UI.
Tech Stack: 
- [x] JavaScript
- [ ] Python
- [ ] Others if yes, mention here : 

GitHub Link: 
https://github.com/Naman-1234/BuildWebOnline

Thank you for this super-impacting initiative.
- [ ] I wish to donate [here](https://www.buymeacoffee.com/imabp) for your efforts, time, and support.

**Comment by imabp** [comment]
We are running bit late. You will hear back by Monday

**Comment by imabp** [comment]
Hello @Naman-1234 
Thanks for your patience.
The project looks awesome and works awesome. I found out, you have well documented it also.
But one thing I suggest was writing meaningful commit messages. As this project I find hard to collaborate on, because of commit messages like.. 
`Little Changes`
`Minor Changes`
Rest all looks good 

To remove unused imports, you can use tree shaking from [Webpack Guides](https://webpack.js.org/guides/tree-shaking/)

Awesome, all the best for the fellowship applications. 
Apply As early as possible.. as there are fixed seats only.
