### ISSUE TITLE
[CODE REVIEW]  <procheta1999>

### ISSUE THREAD

**Issue by procheta1999** [imabp/code-review#18]
Hello, please help me with the code review for the following code sample.

Tech Stack: 
- [x] JavaScript
- [ ] Python
- [ ] Others if yes, mention here : 

GitHub Link: https://github.com/procheta1999/greenhouse_gases.git

Thank you for this super-impacting initiative.
- [ ] I wish to donate [here](https://www.buymeacoffee.com/imabp) for your efforts, time, and support.

**Comment by imabp** [comment]
We are running bit late. You will hear back by Monday

**Comment by procheta1999** [comment]
ok cool

**Comment by imabp** [comment]
Apologies for the latency @procheta1999 
Ongoing through the project, I have figured out this.
- Your Technical Skills regarding data visualization and charts (with static data) are really impressive.
- It would be nice if you can architecture out your readme very well. Like a particular format, you can use this template, as most of us used in Fellowship [imabp/ReadMeTemplates](https://github.com/imabp/ReadMeTemplates)
- I found out, few strings, that can be accessed through a data store, instead of hardcode, just to make sure, things look clean and less noisy ( For Example [here](https://github.com/procheta1999/greenhouse_gases/blob/master/src/pages/components/chart.js#L70-L103))
- Overall, you can update this project, by fetching data through live API(maybe creating a backend), instead of using `input.json` or any static presence of data. It doesn't look nice, from the perspective of a developer.
- Remove boilerplate configuration and code (for ex: [here](https://github.com/procheta1999/greenhouse_gases/blob/master/src/logo.svg)
- Please update Manifest. This is for web previews, whenever you share your website link, to any other platform like WhatsApp or discord, or Twitter. [here](https://github.com/procheta1999/greenhouse_gases/blob/master/public/manifest.json)

Thanks for patience

**Comment by procheta1999** [comment]
Thank you for the review. It is really helpful. I will update my project according to your reviews.
