### ISSUE TITLE
[CODE REVIEW]  vedant-jain03

### ISSUE THREAD

**Issue by vedant-jain03** [imabp/code-review#22]
Hello, please help me with the code review for the following code sample.

Tech Stack: 
- [x] JavaScript
- [ ] Python
- [ ] Others if yes, mention here : 

GitHub Link: https://github.com/vedant-jain03/HashHub

Thank you for this super-impacting initiative.
- [x] I wish to donate [here](https://www.buymeacoffee.com/imabp) for your efforts, time, and support.

**Comment by imabp** [comment]
The graphic design and readme of the site really look attractive.
**But need a lot of work to be done on the Backend so that it shows your technical proficiency for** 
**Open Source and Software Engineering Tracks** 

Make sure, you are displaying a Loading Screen and redirecting the user, whenever he/ she is successfully registered.

Please use some encryption to store passwords, these are some concerns that you have to take care of...

https://github.com/vedant-jain03/Hashhub_backend/blob/515e5aed03913a6c23017b5b7e51bd3db4931d2d/models%20and%20Schema/user.js#L17-L19

I hope you would find this good.
Moreover, I really apologize for such a latency. I was bit busy with my interviews and stuff.. :) Hope you understand...
Let me know, if you need to know more....

**Comment by vedant-jain03** [comment]
> The graphic design and readme of the site really look attractive.
> **But need a lot of work to be done on the Backend so that it shows your technical proficiency for**
> **Open Source and Software Engineering Tracks**
> 
> Make sure, you are displaying a Loading Screen and redirecting the user, whenever he/ she is successfully registered.
> 
> Please use some encryption to store passwords, these are some concerns that you have to take care of...
> 
> https://github.com/vedant-jain03/Hashhub_backend/blob/515e5aed03913a6c23017b5b7e51bd3db4931d2d/models%20and%20Schema/user.js#L17-L19
> 
> I hope you would find this good.
> Moreover, I really apologize for such a latency. I was bit busy with my interviews and stuff.. :) Hope you understand...
> Let me know, if you need to know more....

Thankyou so much abir for reviewing 
For the backend part, I just started learning backend and try to implement it in the project.
Thankyou for telling me the issues I will definitely look into it.
What do you think is it good project?

**Comment by vedant-jain03** [comment]
> The graphic design and readme of the site really look attractive.
> **But need a lot of work to be done on the Backend so that it shows your technical proficiency for**
> **Open Source and Software Engineering Tracks**
> 
> Make sure, you are displaying a Loading Screen and redirecting the user, whenever he/ she is successfully registered.
> 
> Please use some encryption to store passwords, these are some concerns that you have to take care of...
> 
> https://github.com/vedant-jain03/Hashhub_backend/blob/515e5aed03913a6c23017b5b7e51bd3db4931d2d/models%20and%20Schema/user.js#L17-L19
> 
> I hope you would find this good.
> Moreover, I really apologize for such a latency. I was bit busy with my interviews and stuff.. :) Hope you understand...
> Let me know, if you need to know more....

Also best of lucks for your interviews . I am really very glad from your progress.
