### ISSUE TITLE
[CODE REVIEW]  <abhi-824>

### ISSUE THREAD

**Issue by abhi-824** [imabp/code-review#5]
Hello, please help me with the code review for the following code sample.

Tech Stack: 
- [ ] JavaScript
- [ ] HTML/CSS
- [ ] NodeJs

GitHub Link: https://github.com/CodeKaksha/codekaksha_web 

Thank you for this super-impacting initiative.

**Comment by HarshCasper** [comment]
Few suggestions: 

- Add a one-line pitch on the `About` section of the project
- Fix the CK Logo on your README.
- Remove `hack_nagpur_ppt.pptx` from the root and instead put it on Drive and share it through README.
- Most of the commits doesn't make any sense altogether. Also it does not show what parts you actually worked on rather than collaborating with your teammates.
- Remove commented lines of code if you don't need them.
- Your Firebase credentials should not be ideally present in your repository. 
- If you have any awards or honours with this project do mention them on the README itself.
- Clean your Static files (HTML, CSS) to make sure you are not putting in any unused code. It looks like a hot mess right now.
- You have not specified any instructions for setting up `.env` file. Do add the same.

I found the project cool and impactful. Here are some suggestions for your personal application: 

- Highlight the parts that you have developed and worked on. 
- Know the basics well and make sure you review each and every line of code well and understand it. As a sample here are some questions I can ask in a similar situation:
    - Why should you separate Express 'app' and 'server'?
    - What is the difference between a  WebSocket API and a Fetch API?
    - What is Tracing in Node.js?
    - What's a crypt and how do you Cipher the protected information in NodeJS?
- Strategize and divide your time equally between pitching about the project, the parts you worked on and what did you learn?
- Ask and take equivocal feedback from the interviewer. You can ask them the ways you can optimize the codebase and more.

Do let us know if you have any more questions.

**Comment by imabp** [comment]
Hello, @abhi-824  I hope you will work on the above suggestions by @HarshCasper . Thank you @HarshCasper for this :)
And moreover, I feel, you should put up your project architecture on the Readme too. So that it helps to get clear information for other contributors. :) . 
Do let us know, if you have any queries.. 
The issue gets closed in next 24 hours :)

**Comment by imabp** [comment]
We are closing this issue for now, to relieve the overhead. 
But we are listening to you.. Please do let us know, if you have any queries. @abhi-824
