### ISSUE TITLE
[CODE REVIEW]  <Sapna2001>

### ISSUE THREAD

**Issue by Sapna2001** [imabp/code-review#6]
Hello, please help me with the code review for the following code sample.

Tech Stack: 
- [x] JavaScript
- [ ] Python
- [ ] Others if yes, mention here : 

GitHub Link: https://github.com/Sapna2001/Food-Food

Thank you for this super-impacting initiative.
- [ ] I wish to donate [here](https://www.buymeacoffee.com/imabp) for your efforts, time, and support.

**Comment by HarshCasper** [comment]
Few suggestions: 

- Add the deployed link to the repository information so that we can quickly open and view it.
- Remove the ReactJS boilerplate README and add proper instructions to launch the app by adding your instructions.
- Use Netlify/Vercel instead of Heroku to deploy your app. Heroku Apps sleep if not used after some timeD which doesn't bring a very positive impression. 
- You can remove the `.eslintcache` from the repository. 
- Don't keep your App ID and API Key in your code. Learn about setting these credentials through a `.env` file and import them in your code.

Apart from this, I didn't find anything unique with this project. It appears as if a React App has been slapped on an already available API and doesn't look something ingenious. It would be best to ensure that the project has a Developer Focus (AI/ML, Blockchain, Full-Stack, Mobile App, etc.) and an Engineering Focus (Clean Code, Documentation, Deployment, etc.). Combine these ideologies neatly, and you will have an excellent project for the application.

Right now the project is good but appears as if it has been emulated from a tutorial. The tutorial projects are a great way to learn, but they are not suited for these profiles. As the Explorer Track has been discontinued, I'm sceptical that it would pass off something as impactful.

Please let me know if you have any further questions.

**Comment by Sapna2001** [comment]
@HarshCasper thank you for your time and suggestions. I will work on them.
